name: CI - Testes

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm ci

      - name: Rodar testes
        run: npm test

      - name: Criar arquivo .env
        run: echo "EXPO_PUBLIC_TMDB_API_KEY=${{ secrets.TMDB_API_KEY }}" >> .env

      - name: Build do projeto
        run: npx expo export --platform web

      - name: Desabilitar Jekyll
        run: touch dist/.nojekyll

      - name: Upload do artefato
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: test
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy para GitHub Pages
        uses: actions/deploy-pages@v4